[package]
name = "slint_webcam_test"
version = "0.1.0"
edition = "2021"


[dependencies]
slint = "1.3.0"
image = "0.24.7"
anyhow = "1.0.75"

[dependencies.nokhwa]
version = "0.10.4"
features = ["input-native"]


[build-dependencies]
slint-build = "1.3.0"